name: Automatic merging
on:
  status:
  pull_request_target: { types: [opened, synchronize] }
  issue_comment: { types: [created] }
  pull_request_review: { types: [submitted] }


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Codeowners merge check
        uses: casassg/auto-merge-bot@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge_method: 'squash'
